/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_opengl_Renderer */

#ifndef _Included_test_opengl_Renderer
#define _Included_test_opengl_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_opengl_Renderer
 * Method:    nativeInit
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_test_opengl_Renderer_nativeInit
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     test_opengl_Renderer
 * Method:    nativeOnSurfaceCreated
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test_opengl_Renderer_nativeOnSurfaceCreated
  (JNIEnv *, jobject, jlong);

/*
 * Class:     test_opengl_Renderer
 * Method:    nativeOnSurfaceChanged
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_test_opengl_Renderer_nativeOnSurfaceChanged
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     test_opengl_Renderer
 * Method:    nativeDraw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test_opengl_Renderer_nativeDraw
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
