/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_com_gltest_Renderer */

#ifndef _Included_test_com_gltest_Renderer
#define _Included_test_com_gltest_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_com_gltest_Renderer
 * Method:    nativeInit
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_test_com_gltest_Renderer_nativeInit
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     test_com_gltest_Renderer
 * Method:    nativeOnSurfaceCreated
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test_com_gltest_Renderer_nativeOnSurfaceCreated
  (JNIEnv *, jobject, jlong);

/*
 * Class:     test_com_gltest_Renderer
 * Method:    nativeDraw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test_com_gltest_Renderer_nativeDraw
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
